# tomcat
server:
  port: 8080
  servlet:
    context-path: /storehelper
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles: prd
  devtools:
    restart:
      enabled: true      #热加载，每次代码有改动就自动重启
  redis:
    host: 192.168.1.4
    port: 6379
    database: 0
    timeout: 20000
    password: ENC(1Unzpq7aU2CmIBaHmk6m8Q==)
#    cluster:
#      nodes: 192.168.1.1:7001,192.168.1.1:7002,192.168.1.1:7003,192.168.1.1:7004,192.168.1.1:7005,192.168.1.1:7006
#      max-redirects: 3
    lettuce:
      pool:
        max-idle: 30
        min-idle: 0
        max-wait: -1
        max-active: 60
    jedis:
      pool:
        max-idle: 30
        min-idle: 0
        max-wait: -1
        max-active: 60
  datasource:
    ds1:
      driver-class-name: net.sourceforge.jtds.jdbc.Driver
      jdbc-url: jdbc:jtds:sybase://192.168.1.11:50000/laiya;charset=CP936
      username: mis
      password: ENC(jkjsCejtTMsYq7ccwoB2jIzgjfvz5L/8)
      max-idle: 10
      min-idle: 5
      maxActive: 20
      initial-size: 5
      maxWait: 10000
      minIdle: 1
    ds2:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://192.168.1.245;DatabaseName=StoreHelper
      username: IT
      password: ENC(7yt8XW5bxviSYm/XWTQNEb0NPh0cqbwz)
      max-idle: 10
      min-idle: 5
      maxActive: 20
      initial-size: 5
      maxWait: 10000
      minIdle: 1
    ds3:
      driver-class-name: net.sourceforge.jtds.jdbc.Driver
      jdbc-url: jdbc:jtds:sqlserver://192.168.1.8:1433;databaseName=OA
      username: IT
      password: ENC(7yt8XW5bxviSYm/XWTQNEb0NPh0cqbwz)
      max-idle: 10
      min-idle: 5
      maxActive: 20
      initial-size: 5
      maxWait: 10000
      minIdle: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    check-template-location: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: tlg_it
properties:
  api_service:
    defalut_goods_class: DEFAULT|005303,005306,005307,005308,005309,005310,005311,005312,005313,005314
  business_service:
    brand_pic_url: http://192.168.1.4:8080/reshelper/brand/pic/
  erp_service:
    goods_pic_url: http://192.168.1.4:8080/reshelper/goods/pic/